apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-gateway
  template:
    metadata:
      labels:
        app: device-gateway
    spec:
      containers:
      - name: device-gateway
        image: coelee/device-gateway:latest
        ports:
        - containerPort: 5001
      env:
       - name: MQTT_BROKER
         value: "mosquitto-service"
