apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
        - name: log-service
          image: coelee/log-service:latest  # Ganti dengan nama image yang sesuai
          ports:
            - containerPort: 5000
