apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier-service
  template:
    metadata:
      labels:
        app: notifier-service
    spec:
      containers:
        - name: notifier-service
          image: coelee/notifier-service:latest  # Ganti dengan nama image yang sesuai
          ports:
            - containerPort: 5000

